// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: testcounter.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "testcounter.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace hummer {

namespace {

const ::google::protobuf::Descriptor* testcounter_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  testcounter_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_testcounter_2eproto() {
  protobuf_AddDesc_testcounter_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "testcounter.proto");
  GOOGLE_CHECK(file != NULL);
  testcounter_descriptor_ = file->message_type(0);
  static const int testcounter_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(testcounter, counter_),
  };
  testcounter_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      testcounter_descriptor_,
      testcounter::default_instance_,
      testcounter_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(testcounter, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(testcounter, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(testcounter));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_testcounter_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    testcounter_descriptor_, &testcounter::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_testcounter_2eproto() {
  delete testcounter::default_instance_;
  delete testcounter_reflection_;
}

void protobuf_AddDesc_testcounter_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\021testcounter.proto\022\006hummer\"\036\n\013testcount"
    "er\022\017\n\007counter\030\001 \002(\r", 59);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "testcounter.proto", &protobuf_RegisterTypes);
  testcounter::default_instance_ = new testcounter();
  testcounter::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_testcounter_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_testcounter_2eproto {
  StaticDescriptorInitializer_testcounter_2eproto() {
    protobuf_AddDesc_testcounter_2eproto();
  }
} static_descriptor_initializer_testcounter_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int testcounter::kCounterFieldNumber;
#endif  // !_MSC_VER

testcounter::testcounter()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void testcounter::InitAsDefaultInstance() {
}

testcounter::testcounter(const testcounter& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void testcounter::SharedCtor() {
  _cached_size_ = 0;
  counter_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

testcounter::~testcounter() {
  SharedDtor();
}

void testcounter::SharedDtor() {
  if (this != default_instance_) {
  }
}

void testcounter::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* testcounter::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return testcounter_descriptor_;
}

const testcounter& testcounter::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_testcounter_2eproto();
  return *default_instance_;
}

testcounter* testcounter::default_instance_ = NULL;

testcounter* testcounter::New() const {
  return new testcounter;
}

void testcounter::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    counter_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool testcounter::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 counter = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &counter_)));
          set_has_counter();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void testcounter::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 counter = 1;
  if (has_counter()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->counter(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* testcounter::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 counter = 1;
  if (has_counter()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->counter(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int testcounter::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 counter = 1;
    if (has_counter()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->counter());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void testcounter::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const testcounter* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const testcounter*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void testcounter::MergeFrom(const testcounter& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_counter()) {
      set_counter(from.counter());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void testcounter::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void testcounter::CopyFrom(const testcounter& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool testcounter::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void testcounter::Swap(testcounter* other) {
  if (other != this) {
    std::swap(counter_, other->counter_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata testcounter::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = testcounter_descriptor_;
  metadata.reflection = testcounter_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace hummer

// @@protoc_insertion_point(global_scope)
