// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: testcounter.proto

#ifndef PROTOBUF_testcounter_2eproto__INCLUDED
#define PROTOBUF_testcounter_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace hummer {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_testcounter_2eproto();
void protobuf_AssignDesc_testcounter_2eproto();
void protobuf_ShutdownFile_testcounter_2eproto();

class testcounter;

// ===================================================================

class testcounter : public ::google::protobuf::Message {
 public:
  testcounter();
  virtual ~testcounter();

  testcounter(const testcounter& from);

  inline testcounter& operator=(const testcounter& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const testcounter& default_instance();

  void Swap(testcounter* other);

  // implements Message ----------------------------------------------

  testcounter* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const testcounter& from);
  void MergeFrom(const testcounter& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 counter = 1;
  inline bool has_counter() const;
  inline void clear_counter();
  static const int kCounterFieldNumber = 1;
  inline ::google::protobuf::uint32 counter() const;
  inline void set_counter(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:hummer.testcounter)
 private:
  inline void set_has_counter();
  inline void clear_has_counter();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 counter_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_testcounter_2eproto();
  friend void protobuf_AssignDesc_testcounter_2eproto();
  friend void protobuf_ShutdownFile_testcounter_2eproto();

  void InitAsDefaultInstance();
  static testcounter* default_instance_;
};
// ===================================================================


// ===================================================================

// testcounter

// required uint32 counter = 1;
inline bool testcounter::has_counter() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void testcounter::set_has_counter() {
  _has_bits_[0] |= 0x00000001u;
}
inline void testcounter::clear_has_counter() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void testcounter::clear_counter() {
  counter_ = 0u;
  clear_has_counter();
}
inline ::google::protobuf::uint32 testcounter::counter() const {
  return counter_;
}
inline void testcounter::set_counter(::google::protobuf::uint32 value) {
  set_has_counter();
  counter_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace hummer

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_testcounter_2eproto__INCLUDED
