/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "hbase_constants.h"

namespace apache { namespace hadoop { namespace hbase { namespace thrift {

const hbaseConstants g_hbase_constants;

hbaseConstants::hbaseConstants() {
  LATEST_TIMESTAMP = 9223372036854775807LL;

}

}}}} // namespace

